# Broadcasting with `volkit.future`

This notebook shows how inputs broadcast across shapes in `price_euro_future`.

**Key points**:
- Any scalar or array arguments are **broadcasted** to a common shape.
- `cp` can be `+1/-1` or `'call'/'put'`, and also broadcasts.
- Results return with the broadcasted shape.


In [1]:
import numpy as np
from volkit.future import price_euro_future

np.set_printoptions(precision=6, suppress=True)

## Example 1 — 1D broadcast (vector `F`, scalar `K,T,r,σ`, scalar `cp`)


In [2]:
F = np.array([90.0, 100.0, 110.0])
K = 100.0
T = 0.5
r = 0.02
sigma = 0.20
cp = 'call'
p1 = price_euro_future(F, K, T, r, sigma, cp)
print('Example 1 shape:', p1.shape)
print(p1)

Example 1 shape: (3,)
[ 1.754815  5.581107 12.089743]


## Example 2 — `cp` as a vector
We mix calls and puts in one call.

In [4]:
cp_vec = np.array(['call', 'put', 'call'])
p2 = price_euro_future(F, K, T, r, sigma, cp_vec)
print('Example 2 shape:', p2.shape)
print(p2)



Example 2 shape: (3,)
[ 1.754815  5.581107 12.089743]


## Example 3 — 2D broadcast (rows × cols) and broadcasting `cp`
Here shapes are `(2,1)` × `(1,3)` → output `(2,3)`.

In [7]:
F2 = np.array([[90.0], [110.0]])        # (2,1)
K2 = np.array([[80.0, 100.0, 120.0]])   # (1,3)
T2 = 1.25
r2 = 0.00
sigma2 = np.array([[0.15], [0.25]])     # (2,1)
cp2 = np.array([['call'], ['put']])     # (2,1)

p3 = price_euro_future(F2, K2, T2, r2, sigma2, cp2)
print('Example 3 shape:', p3.shape)
print(p3)

# Sanity: compare with explicit expanded arrays (manual broadcast)
shape = np.broadcast(F2, K2, T2, r2, sigma2, cp2).shape
F2b, K2b, T2b, r2b, s2b, cp2b = (np.broadcast_to(x, shape) for x in (F2, K2, T2, r2, sigma2, cp2))
p3_manual = price_euro_future(F2b, K2b, T2b, r2b, s2b, cp2b)
print('Max abs diff to manual broadcast:', np.max(np.abs(p3 - p3_manual)))

Example 3 shape: (2, 3)
[[12.021202  2.557496  0.306144]
 [ 1.652928  7.337307 18.391679]]
Max abs diff to manual broadcast: 0.0
